# Generated by Django 4.0.1 on 2022-01-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phone_contact_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
